### ISSUE TITLE
Provide free & premium tier products in Azure API Management

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/sello#25]
Provide premium & free tier products in Azure API Management.

This allows us to illustrate how you can throttle based on the pricing plan they have with Sello.

Throttling needs to be applied:
- **Premium Plan :** 10k calls per second
- **Free Plan:** 10 calls per minute

**Task List:**
- [x] Create Premium Product
- [x] Create Free Product
- [x] Add generic throttling policy
- [x] Apply throttling policy for Premium 
- [x] Apply throttling policy for Free
- [x] Update documentation

Depends on #4
